apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: pipeline-greeter
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            # to make sure new pipeline builds gets new image always
            imagePullPolicy: Always
            livenessProbe:
              httpGet:
                path: /health
            readinessProbe:
              httpGet:
                path: /health
